<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="bankingserviceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/bankingserviceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/bankingserviceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://services.aic666.tuwien.at/">
    <import location="http://localhost:8084/bankingservice?wsdl" namespace="http://services.aic666.tuwien.at/"/>
    <plnk:partnerLinkType name="IBankingServiceLinkType">
        <plnk:role name="IBankingServiceRole" portType="ns:IBankingService"/>
    </plnk:partnerLinkType>
</definitions>

