<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="customersoapWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/customersoapWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/customersoapWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://services.aic666.tuwien.at/">
    <import location="http://localhost:8086/customersoap?wsdl" namespace="http://services.aic666.tuwien.at/"/>
    <plnk:partnerLinkType name="CustomerManagementSoapLinkType">
        <plnk:role name="CustomerManagementSoapRole" portType="ns:CustomerManagementSoap"/>
    </plnk:partnerLinkType>
</definitions>

