
package at.ac.tuwien.infosys.aic.registry;

import java.io.File;
import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.4
 * Thu Jan 14 17:08:07 CET 2010
 * Generated source version: 2.2.4
 * 
 */
 
public class RegistryService_RegistryServicePort_Server{

    protected RegistryService_RegistryServicePort_Server() throws Exception {
        System.out.println(new File("name").getAbsolutePath());
        System.out.println("Starting Server");
        Object implementor = new RegistryServiceImpl();
        String address = "http://localhost:8087/registry";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new RegistryService_RegistryServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
