
/*
 * 
 */

package at.ac.tuwien.infosys.aic.registry;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Thu Jan 14 17:08:07 CET 2010
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "RegistryService", 
                  wsdlLocation = "resources/registry.wsdl",
                  targetNamespace = "http://www.infosys.tuwien.ac.at/ait09/registry") 
public class RegistryService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.infosys.tuwien.ac.at/ait09/registry", "RegistryService");
    public final static QName RegistryServicePort = new QName("http://www.infosys.tuwien.ac.at/ait09/registry", "RegistryServicePort");
    static {
        URL url = null;
        try {
            url = new URL("resources/registry.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/registry.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RegistryService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistryService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns RegistryService
     */
    @WebEndpoint(name = "RegistryServicePort")
    public RegistryService getRegistryServicePort() {
        return super.getPort(RegistryServicePort, RegistryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistryService
     */
    @WebEndpoint(name = "RegistryServicePort")
    public RegistryService getRegistryServicePort(WebServiceFeature... features) {
        return super.getPort(RegistryServicePort, RegistryService.class, features);
    }

}
